version: v1
name: changelog-generator
namespace: ci

prompts:
  - name: default
    messages:
      - role: system
        content: |
          You are the official changelog writer for LlamaFarm, an open-source local AI platform.
          Your sole purpose is to transform conventional commit changelogs into polished,
          human-readable release notes that users will enjoy reading.

          Your writing style:
          - Professional yet approachable, like a friendly colleague sharing exciting updates
          - Clear and concise, respecting the reader's time
          - Focused on user impact, not implementation details

          Structure your output as follows:
          1. Start with a brief 1-2 sentence summary of the release theme
          2. Group changes into logical sections (e.g., "New Features", "Improvements", "Bug Fixes")
          3. For each change, explain WHAT users can now do and WHY it matters

          Rules:
          - Never include commit hashes, PR numbers, or issue references
          - Never use bullet points that just repeat the commit message
          - Avoid technical jargon unless the audience needs it
          - If multiple commits relate to the same feature, combine them into one narrative
          - Output in markdown format

rag:
  data_processing_strategies:
    - description: Unified processor for PDFs, Word docs, CSVs, Markdown, and text files
      extractors:
        - config:
            include_readability: true
            include_structure: true
            include_vocabulary: true
          file_include_patterns:
            - "*"
          priority: 10
          type: ContentStatisticsExtractor
        - config:
            entity_types:
              - PERSON
              - ORG
              - GPE
              - DATE
              - PRODUCT
              - MONEY
              - PERCENT
            min_entity_length: 2
            use_fallback: true
          file_include_patterns:
            - "*"
          priority: 20
          type: EntityExtractor
        - config:
            algorithm: yake
            max_keywords: 10
            min_keyword_length: 3
          file_include_patterns:
            - "*"
          priority: 30
          type: KeywordExtractor
        - config:
            extract_headers: true
            merge_cells: true
            output_format: dict
          file_include_patterns:
            - "*.pdf"
            - "*.PDF"
          priority: 5
          type: TableExtractor
        - config:
            extract_relative: true
            extract_times: true
            formats:
              - ISO8601
              - US
              - EU
          file_include_patterns:
            - "*.csv"
            - "*.xlsx"
            - "*.xls"
            - "*.tsv"
          priority: 5
          type: DateTimeExtractor
        - config:
            custom_patterns:
              - description: Python function definitions
                name: function_def
                pattern: def\s+\w+\s*\(
              - description: Class definitions
                name: class_def
                pattern: class\s+\w+[\(\:]
            predefined_patterns:
              - email
              - url
              - ip_address
              - version
          file_include_patterns:
            - "*.py"
            - "*.js"
            - "*.java"
            - "*.cpp"
            - "*.c"
            - "*.h"
          priority: 5
          type: PatternExtractor
        - config:
            extract_outline: true
            include_hierarchy: true
            max_level: 6
          file_include_patterns:
            - "*.md"
            - "*.markdown"
            - README*
          priority: 5
          type: HeadingExtractor
        - config:
            extract_domains: true
            extract_emails: true
            extract_urls: true
          file_include_patterns:
            - "*.md"
            - "*.markdown"
            - "*.html"
            - "*.htm"
          priority: 10
          type: LinkExtractor
      name: universal_processor
      parsers:
        - config:
            chunk_overlap: 50
            chunk_size: 300
            chunk_strategy: semantic
            extract_metadata: true
            extract_tables: true
          file_include_patterns:
            - "*.pdf"
            - "*.PDF"
          priority: 10
          type: PDFParser_LlamaIndex
        - config:
            chunk_overlap: 50
            chunk_size: 300
            chunk_strategy: paragraphs
            combine_pages: false
            extract_metadata: true
          file_include_patterns:
            - "*.pdf"
            - "*.PDF"
          priority: 50
          type: PDFParser_PyPDF2
        - config:
            chunk_overlap: 100
            chunk_size: 500
            extract_metadata: true
            extract_tables: true
          file_include_patterns:
            - "*.docx"
            - "*.DOCX"
          priority: 10
          type: DocxParser_LlamaIndex
        - config:
            chunk_size: 400
            chunk_strategy: sections
            extract_code_blocks: true
            extract_links: true
            extract_metadata: true
          file_include_patterns:
            - "*.md"
            - "*.markdown"
            - "*.mdown"
            - "*.mkd"
            - README*
          priority: 10
          type: MarkdownParser_Python
        - config:
            chunk_size: 1000
            chunk_strategy: rows
            encoding: utf-8
            extract_metadata: true
          file_include_patterns:
            - "*.csv"
            - "*.CSV"
            - "*.tsv"
            - "*.TSV"
            - "*.dat"
          priority: 10
          type: CSVParser_Pandas
        - config:
            chunk_size: 500
            extract_metadata: true
          file_include_patterns:
            - "*.xlsx"
            - "*.XLSX"
            - "*.xls"
            - "*.XLS"
          priority: 10
          type: ExcelParser_Pandas
        - config:
            chunk_overlap: 100
            chunk_size: 500
            chunk_strategy: sentences
            clean_text: true
            encoding: utf-8
            extract_metadata: true
          file_include_patterns:
            - "*.txt"
            - "*.text"
            - "*.log"
            - "*.json"
            - "*.xml"
            - "*.yaml"
            - "*.yml"
            - "*.toml"
            - "*.cfg"
            - "*.conf"
            - "*.ini"
            - "*.py"
            - "*.js"
            - "*.java"
            - "*.cpp"
            - "*.c"
            - "*.h"
            - "*.sh"
            - "*.bash"
            - "*.zsh"
            - LICENSE*
            - CHANGELOG*
            - AUTHORS*
          priority: 50
          type: TextParser_Python
  databases:
    - config:
        collection_name: documents
        distance_function: cosine
        persist_directory: ./data/chroma_db
      default_embedding_strategy: default_embeddings
      default_retrieval_strategy: basic_search
      embedding_strategies:
        - config:
            auto_pull: true
            batch_size: 16
            dimension: 384
            model: sentence-transformers/all-MiniLM-L6-v2
            timeout: 60
          name: default_embeddings
          type: UniversalEmbedder
      name: main_database
      retrieval_strategies:
        - config:
            distance_metric: cosine
            top_k: 10
          default: true
          name: basic_search
          type: BasicSimilarityStrategy
        - config:
            fallback_multiplier: 2
            filter_mode: post
            top_k: 10
          name: filtered_search
          type: MetadataFilteredStrategy
      type: ChromaStore
  default_database: main_database

runtime:
  models:
    - description: Default Universal model
      model: unsloth/Qwen3-4B-GGUF:Q5_K_M
      name: default
      prompts:
        - default
      provider: universal
      tool_call_strategy: native_api
      model_api_parameters:
        max_tokens: 16384
      extra_body:
        n_ctx: 20000
