version: v1
name: many_small_file_demo
namespace: default

runtime:
  models:
    - name: default
      description: "Default Ollama model for small file analysis"
      provider: ollama
      model: llama3.1:8b
      base_url: http://localhost:11434
      default: true
      prompt_format: unstructured

prompts:
  - name: default
    messages:
      - role: system
        content:
          "You are a helpful assistant analyzing multiple small documents.

          Always cite the specific file name when referencing information.

          If a question cannot be answered using the provided context, state that clearly.

          "

rag:
  databases:
    - name: small_pdfs_db
      type: ChromaStore
      config:
        collection_name: small_pdfs
        distance_function: cosine
        persist_directory: ./data/small_pdfs_db
        port: 8000
      embedding_strategies:
        - name: default_embeddings
          type: UniversalEmbedder
          config:
            model: nomic-ai/nomic-embed-text-v2-moe
            dimension: 768
            batch_size: 16
            timeout: 60
            auto_pull: true
          priority: 0
      retrieval_strategies:
        - name: targeted_letters
          type: BasicSimilarityStrategy
          config:
            distance_metric: cosine
            top_k: 8
          default: true
      default_embedding_strategy: default_embeddings
      default_retrieval_strategy: targeted_letters
  data_processing_strategies:
    - name: universal_processor
      description: Parser tuned for small PDFs
      parsers:
        - type: PDFParser_LlamaIndex
          file_include_patterns:
            - "*.pdf"
            - "*.PDF"
          priority: 100
          config:
            chunk_size: 1200
            chunk_overlap: 150
            chunk_strategy: semantic
            extract_metadata: true
        - type: PDFParser_PyPDF2
          file_include_patterns:
            - "*.pdf"
            - "*.PDF"
          priority: 50
          config:
            chunk_size: 1000
            chunk_overlap: 120
            chunk_strategy: paragraphs
            extract_metadata: true
      extractors:
        - type: ContentStatisticsExtractor
          file_include_patterns:
            - "*"
          priority: 100
          config:
            include_readability: true
            include_structure: true
        - type: EntityExtractor
          file_include_patterns:
            - "*"
          priority: 90
          config:
            entity_types:
              - ORG
              - DATE
              - PERSON
              - PRODUCT
            min_entity_length: 2
            use_fallback: true

datasets:
  - name: small_pdfs
    data_processing_strategy: universal_processor
    database: small_pdfs_db
